name: timo_anno
description: Annotations defined for dart code generator.
version: 1.0.0
environment: {sdk: ">=3.1.5 <4.0.0"}

# Please import this package via github
# because this package had not been published to pub.dev yet.
# This option will also enable local imports.
publish_to: "none"

dev_dependencies:
  timo_lints: {path: ../lints}
