name: timo_gen_example
description: Example for Dart code generating.
version: 0.0.0
environment: {sdk: ">=3.1.5 <4.0.0"}
publish_to: "none"

dependencies:
  flutter: {sdk: flutter}
  timo_anno: {path: ../../anno}

dev_dependencies:
  timo_lints: {path: ../../lints}
  timo_gen: {path: ../}
  build_runner: ^2.4.6
