name: timo_widgets
description: Shared flutter widgets for the Timo Project.
version: 0.0.0
environment: {sdk: ">=3.1.5 <4.0.0"}
publish_to: "none"

dependencies:
  flutter: {sdk: flutter}

dev_dependencies:
  flutter_test: {sdk: flutter}
  timo_lints: {path: ../lints}
