# see https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md
builders:
  state_data_builder:
    import: "package:timo_gen/builders.dart"
    builder_factories: ["stateDataBuilder"]
    build_extensions: {".dart": [".data.g.dart"]}
    auto_apply: dependents
    build_to: source
